spring:
  # nacos ??
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8812
    gateway:
      routes: # ????
        - id: system-service # ??????
          # uri: http://127.0.0.1:8000 ????????
          uri: lb://cloud-system-service  # ?nacos??????,lb?????????
          predicates: #?? ?????????
            # - Path=/v1/**
            - Query=name,test|test2|test3 #http://localhost:8002/v1/user/list?name=test
            - After=2021-03-18T17:32:58.129+08:00[Asia/Shanghai]
            - CheckParam=test
          filters: # ???????????????????
            - CheckParam=1

      # ??????nacos??
      discovery:
        locator:
          #??????nacos????????? ??? ?????
          # ??????????????????????????????
          enabled: false
    # sentinel ??
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 9904

  #dashboard: 8080 ?????
  #port: 9904 ???????????????????dashboard????????????????????? Http Server?? Server ?? Sentinel ??????, ????,???+1????
  # ??????
  zipkin:
    base-url: http://81.69.43.78:9411/ #zipkin??
    discovery-client-enabled: false  #????????
  # ??????????
  sleuth:
    sampler:
      probability: 1.0 #?????

  # redis????
  redis:
    host: 127.0.0.1
    database: 5
    port: 6379
    password:
    jedis:
      pool:
        # ?????????????????
        max-active: 100
        # ??????????? -1 ??????
        max-wait: -1ms
        # ??????????
        max-idle: 10
        # ??????????
        min-idle: 0
    # ??????????
    timeout: 1000

