spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: tjz0922
  # 全局的返回前端的时间格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # nacos 地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8812
    # sentinel 配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:8089
        port: 9900
  # 收集链路信息
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin地址
    discovery-client-enabled: true  #不用开启服务发现
  # 设置链路追踪采样比例
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
  # redis相关配置
  redis:
    host: 127.0.0.1
    database: 6
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数，负值表示没有限制
        max-active: 100
        # 连接池最大阻塞等待时间 -1 表示没有限制
        max-wait: -1ms
        # 连接池中最大空闲连接
        max-idle: 10
        # 连接池中最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000